const $=id=>document.getElementById(id);
const examples={customers:'SELECT * FROM Customers;',orders:'SELECT * FROM Orders;',totals:'SELECT Customers.Name, SUM(Orders.TotalAmount) AS TotalSpent\nFROM Customers\nJOIN Orders ON Customers.CustomerID = Orders.CustomerID\nGROUP BY Customers.Name\nORDER BY TotalSpent DESC;',count:'SELECT COUNT(*) AS UzsakymuSkaicius FROM Orders;'};
let worker,timer;
function status(text,error=false){$('sql-status').textContent=text;$('sql-status').classList.toggle('error',error);}
function init(){clearTimeout(timer);worker?.terminate();$('run').disabled=true;$('results').replaceChildren();status('Įkeliama pradinė duomenų bazė…');worker=new Worker('worker.js');worker.onmessage=({data})=>{clearTimeout(timer);if(data.type==='ready'){status('Duomenų bazė paruošta. Įrašyk užklausą.');$('run').disabled=false;}else if(data.type==='error'){status('Užklausos ar įkėlimo klaida: '+data.message,true);$('run').disabled=false;}else if(data.type==='result'){render(data.results);$('run').disabled=false;}};worker.onerror=()=>{clearTimeout(timer);status('Nepavyko įkelti SQL priemonės. Atverk svetainę per HTTP adresą ir spausk „Atkurti duomenis“.',true);$('run').disabled=true;};worker.postMessage({type:'init'});timer=setTimeout(()=>{worker.terminate();status('Duomenų įkėlimas užtruko per ilgai. Spausk „Atkurti duomenis“ ir bandyk dar kartą.',true);},20000);}
function render(results){$('results').replaceChildren();let rows=0;for(const result of results){if(!result.columns.length)continue;const wrap=document.createElement('div');wrap.className='table-scroll';const table=document.createElement('table');const thead=document.createElement('thead'),tr=document.createElement('tr');for(const column of result.columns){const th=document.createElement('th');th.textContent=column;tr.append(th);}thead.append(tr);table.append(thead);const tbody=document.createElement('tbody');for(const row of result.values){const line=document.createElement('tr');for(const value of row){const cell=document.createElement('td');cell.textContent=value===null?'NULL':String(value);line.append(cell);}tbody.append(line);}rows+=result.values.length;table.append(tbody);wrap.append(table);$('results').append(wrap);if(result.truncated){const note=document.createElement('p');note.className='hint';note.textContent='Rezultatas sutrumpintas: parodyta pirmųjų 500 eilučių. Patikslink užklausą arba naudok LIMIT.';$('results').append(note);}}status('Užklausa įvykdyta. Rodoma eilučių: '+rows+'.');}
$('examples').addEventListener('change',event=>{$('query').value=examples[event.target.value];});
$('restore').addEventListener('click',init);
$('run').addEventListener('click',()=>{const query=$('query').value.trim();if(!query){status('Įrašyk SQL užklausą.',true);return;}$('run').disabled=true;status('Vykdoma užklausa…');$('results').replaceChildren();worker.postMessage({type:'query',query});timer=setTimeout(()=>{worker.terminate();$('run').disabled=true;status('Užklausa viršijo 5 sekundžių ribą. Spausk „Atkurti duomenis“ ir supaprastink užklausą.',true);},5000);});
init();
