const $ = id => document.getElementById(id);
const exampleText = `Mokinys mokosi. Mokinys kuria. Mokinys mokosi ir klausia. Mokytojas klausia ir klausosi. Mokinys klausia, o mokytojas paaiškina. Mokinys kuria programą. Programa skaičiuoja. Programa kuria tekstą. Tekstas pasakoja istoriją. Istorija žadina smalsumą. Smalsumas padeda mokytis. Mokinys mokosi ir kuria. Mokinys mokosi. Mokinys kuria žaidimą. Žaidimas padeda mokytis. Mokinys atranda naują idėją. Idėja virsta programa. Programa padeda mokytis.`;
let worker, sequence = 0, version = 0, trainedVersion = -1, busy = false, generatedText = '';
const pending = new Map();
function updateControls() { const disabled = busy || version !== trainedVersion; $('train').disabled=busy; $('generate').disabled=disabled; $('inspect').disabled=disabled; }
function setStatus(id, text, error=false) { $(id).textContent=text; $(id).classList.toggle('error',error); }
function startWorker() {
  worker = new Worker('worker.mjs', {type:'module'});
  worker.onmessage = ({data}) => { const task=pending.get(data.id); if(!task)return; pending.delete(data.id); clearTimeout(task.timer); data.error ? task.reject(new Error(data.error)) : task.resolve(data.result); };
  worker.onerror = () => failWorker('Nepavyko paleisti modelio. Atverk puslapį per svetainės adresą arba vietinį serverį.');
}
function failWorker(message) { worker?.terminate(); worker=null; trainedVersion=-1; for(const task of pending.values()){clearTimeout(task.timer);task.reject(new Error(message));}pending.clear(); updateControls(); }
function request(type, payload) { if(!worker)startWorker();return new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>failWorker('Skaičiavimas užtruko per ilgai. Pabandyk trumpesnį tekstą.'),20000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,type,...payload});}); }
function invalidate() { version++; trainedVersion=-1; $('tokens').textContent=$('words').textContent=$('pairs').textContent='—';$('probabilities').replaceChildren();$('prob-caption').textContent='Tekstas pakeistas. Apmokyk modelį iš naujo.';$('prob-note').textContent='';setStatus('training-status','Tekstas pakeistas. Spausk „Apmokyti modelį“.');setStatus('generation-status','Pirmiausia apmokyk modelį.');updateControls(); }
$('training-text').addEventListener('input',invalidate);
$('example').addEventListener('click',()=>{$('training-text').value=exampleText;invalidate();});
$('text-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(file.size>2_000_000){setStatus('training-status','Failas per didelis. Pasirink iki 2 MB TXT failą.',true);event.target.value='';return;}try{$('training-text').value=await file.text();invalidate();setStatus('training-status','Tekstas įkeltas. Spausk „Apmokyti modelį“.');}catch{setStatus('training-status','Nepavyko perskaityti failo.',true);}event.target.value='';});
$('train').addEventListener('click',async()=>{const taskVersion=version;busy=true;updateControls();setStatus('training-status','Skaičiuojamos žodžių poros…');try{const data=await request('train',{text:$('training-text').value});if(taskVersion!==version){setStatus('training-status','Apmokymo metu tekstas pasikeitė. Apmokyk dar kartą.');return;}trainedVersion=version;for(const key of ['tokens','words','pairs'])$(key).textContent=data[key].toLocaleString('lt');if(!$('seed').value.trim())$('seed').value=data.first;setStatus('training-status','Modelis apmokytas. Dabar gali generuoti tekstą.');setStatus('generation-status','Modelis pasirengęs. Pasirink pradinį žodį.');await inspect();}catch(error){trainedVersion=-1;setStatus('training-status',error.message,true);}finally{busy=false;updateControls();}});
function correction(start) {return start.corrected ? `Žodžio „${start.requested}“ nėra. Pasirinktas panašiausias žodis „${start.word}“.` : `Pradinis žodis: „${start.word}“.`;}
async function inspect(){const data=await request('inspect',{input:$('seed').value});$('prob-caption').textContent=`Kas gali eiti po „${data.start.word}“? ${data.start.corrected?correction(data.start):''}`;$('probabilities').replaceChildren();for(const choice of data.choices){const row=document.createElement('div');row.className='prob-row';const name=document.createElement('span');name.textContent=choice.word;const bar=document.createElement('span');bar.className='prob-bar';const fill=document.createElement('i');fill.style.width=`${choice.probability*100}%`;bar.append(fill);const value=document.createElement('span');value.textContent=choice.probability.toLocaleString('lt',{style:'percent',maximumFractionDigits:1});row.append(name,bar,value);$('probabilities').append(row);}$('prob-note').textContent=data.total>12?`Rodoma 12 iš ${data.total} galimų tęsinių. Likę tęsiniai taip pat dalyvauja generavime.`:'Rodomi visi galimi tęsiniai. Tikimybių suma lygi 100 %.';}
$('inspect').addEventListener('click',async()=>{busy=true;updateControls();try{await inspect();setStatus('generation-status','Tikimybės atnaujintos.');}catch(error){setStatus('generation-status',error.message,true);}finally{busy=false;updateControls();}});
$('generate-form').addEventListener('submit',async event=>{event.preventDefault();if(busy||version!==trainedVersion)return;busy=true;updateControls();setStatus('generation-status','Generuojamas tekstas…');try{const data=await request('generate',{input:$('seed').value,length:Number($('length').value)});generatedText=data.text;$('generated').textContent=generatedText;$('download').disabled=false;setStatus('generation-status',correction(data.start)+' Sugeneruota elementų: '+data.tokens.length+'.');await inspect();}catch(error){setStatus('generation-status',error.message,true);}finally{busy=false;updateControls();}});
$('download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([generatedText],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='modelio-tekstas.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('training-text').value=exampleText;
